Dev
frontend-park-mail-ru/2020_2_Ruiners pull request #86
Opened 2020-11-06 21:29 UTC by ErikDoter

2020-11-08 22:48 UTC, dreamofdark requested changes

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Button/Button.css
> +.buttons {
компонент же Button, почему класс buttons?))

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Button/Button.css
> +}
это должны быть элементы по БЭМу
и вообще в данном случае скорее margin должен задаваться внутри родителя

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Button/Button.js
> +      this.button.addEventListener('click', (evt) => {
если callback нет, то все сломается

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.css
> +.myComment__underground {
рутовый стиль лучше называть как компонент

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.css
> +    max-height: 20%;
выглядит так себе, не думаю что будет нормально смотреться на мобилке

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.css
> +    font-family: 'Montserrat', sans-serif;
шрифты надо вынести в css переменные

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.css
> +textarea.question + label > span {
такие сложные селекторы лучше не делать
1. они могут сломаться при изменении верстки
2. выглядит оч нечитабельно
3. влияет на производительность

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.css
> +}
почему такая мешанина в comment, и логин и профайл
это же все элементы компонента comments

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Comments/Comments.handlebars
> +            <hr class="myLine">
что такое myLine

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +export default class FilmCard {
перед классом надо сделать ентре

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +    constructor(context = {}) {
а перед конструктором ентер не нужен

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +      this.mapRussian['Фантастика'] = 'fantasy';
почему жанры в компоненте захардкожены?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +      this.voteButton = new Button({
кажется логичнее делать это в рендере

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +      if(this.isAuthorized) {
пробел перед if

кажется стоит прогнать линтер

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmCard/FilmCard.js
> +                          .then((res) => {
почему запрос в компоненте??
компонент должны отвечать только за отрисовку

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmLenta/FilmLenta.js
> +      for( let i = 0; i < this.body.length; i++) {
это тоже лучше делать в рендере

не надо смешивать отрисовку и инициализацию

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/FilmPoster/FilmPoster.js
> +        title, MainGenre, year, SmallImg, id
почему какие-то пропсы с большой а какие-то сс маленькой бувы начинаются?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Footer/Footer.css
> +.custom__footer {
как футер может быть кастом, если в верстке ниже вы используете это как рутовый класс?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Form/Form.css
> +form main {
не привязывайте стили к тэгам, задайте классы

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/List/List.css
> +}
что за райт/лефт, не понятно что ето

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/Nav/Nav.css
> +    padding: 0 3em;
почему em?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/PersonCard/PersonCard.handlebars
> +    </div>
что-то не логично, если вы используете этот класс и для даты и для места рождения, наверно ему стоит дать более общее название

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.css
> +.okno {
?!?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.css
> +    margin-left: -80px;
сомнительно выглдяит

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.css
> +    -webkit-border-radius: 58px;
расскажи плиз для чего вы их используете?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.js
> +export default class Window {
что такое WIndow? Может путаться с window глобальным

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.js
> +import Bus from "../../Services/EventBus.js";
линтер!

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Components/window/Window.js
> +import Button from "../Button/Button.js";
сделайте alias путей в вебпаке

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/EventBus.js
> +        this.listeners[ event ] = this.listeners[ event ]
листнеров для того события может не быть и все сломается

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +        console.log("sss", allPath);
уберите логирование или сделайте нормальный инструмент для этого

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +            if (!(event.target instanceof HTMLAnchorElement) && !(event.target instanceof HTMLImageElement)) {
зачем картинку проверять?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +            if (target instanceof HTMLImageElement) {
если уж вам надо, вынесите instanceof HTMLImageElement в константу

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +            const target = event.target;
деструктуризуйте в самом начале, там вы тоже используете target

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +            if (link.pathname.indexOf('undefined') !== -1) {
ну чет не оч
выглядит как максимальный костыль

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +        }.bind(this));
сделайте стрелочные функции вместо bind

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/Router.js
> +}
давайте попробуем переписать это в более функциональном стиле

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/filmService.js
> +import { AjaxModule } from '../modules/ajax1.js';
скоро сиквел ajax?)))

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/filmService.js
> +            data.errmsg = 'Пусто';
Тексты ошибок лучше делать более продуманнными

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/filmService.js
> +        const data = { ok: false, errmsg: undefined, get: undefined };
для этих целей есть null, undefined лучше не присваивать самим

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/filmService.js
> +            data.errmsg = 'хз';
-_-

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Services/rateAndReviewService.js
> +  static async Rate(filmId, rating) {
у вас есть какая-то логика наименования? почему тут с большой буквы, а в других файлах с маленькой?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Views/FilmPage.js
> +      super(nav);
откуда переменная nav?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Views/FilmPage.js
> +      body.className = 'film1';
что за film1?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Views/FilmPage.js
> +                  actors = JSON.parse(JSON.stringify(res.get));
зачем вы так делаете?

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Views/FilmPage.js
> +                  Bus.emit('main');
непонятно что значит это событие

2020-11-08 22:48 UTC, dreamofdark commented on kinopoisk/public/Views/Navbar.js
> +      let windowClicks = 0;
почему бы просто не сделать флаг isOpen и менять уже его?)

2020-11-09 12:08 UTC, ErikDoter commented on kinopoisk/public/Components/window/Window.css
> +    -webkit-border-radius: 58px;
Для треугольничка, когда нажимаем на профиль

2020-11-09 13:15 UTC, dreamofdark commented on kinopoisk/public/Services/filmService.js
> +            data.errmsg = 'Нетфильмов с таким актером';
пробел потерялся

2020-11-09 14:12 UTC, merged